import { Account, Client, Databases } from 'react-native-appwrite';

export const client = new Client()
.setEndpoint(process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT!)
.setProject(process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID!)
.setPlatform(process.env.EXPO_PUBLIC_APPWRITE_PLATFORM!)

export const databases = new Databases(client);
export const account = new Account(client);

export const DATABASE_ID = process.env.EXPO_PUBLIC_DB_ID!;
export const HEALTHLOG_COLLECTION_ID = 
process.env.EXPO_PUBLIC_DAILYHEALTH_COLLECTION_ID!;

export const STEPS_DAILY_COLLECTION_ID =
process.env.EXPO_PUBLIC_STEPS_DAILY_COLLECTION_ID!;

export const STEPS_SUMMARY_COLLECTION_ID =
process.env.EXPO_PUBLIC_STEPS_SUMMARY_COLLECTION_ID!;

export const PERIOD_LOGS_COLLECTION_ID = process.env.EXPO_PUBLIC_PERIOD_LOGS_COLLECTION_ID!;
export const PCOS_LOGS_COLLECTION_ID = process.env.EXPO_PUBLIC_PCOS_LOGS_COLLECTION_ID!;
export const CALORIE_GOALS_COLLECTION_ID = process.env.EXPO_PUBLIC_CALORIE_GOALS_COLLECTION_ID!;
export const STEPS_GOALS_COLLECTION_ID = process.env.EXPO_PUBLIC_STEPS_GOALS_COLLECTION_ID!;
export const NUTRITION_LOGS_COLLECTION_ID = process.env.EXPO_PUBLIC_NUTRITION_LOGS_COLLECTION_ID!;
export const WEIGHT_LOGS_COLLECTION_ID =process.env.EXPO_PUBLIC_WEIGHT_LOGS_COLLECTION_ID!;
//export const COMMUNITY_PROFILES_COLLECTION_ID = process.env.EXPO_PUBLIC_COMMUNITY_PROFILES_COLLECTION_ID!;
export const CHALLENGES_COLLECTION_ID =process.env.EXPO_PUBLIC_CHALLENGES_COLLECTION_ID!;
export const CHALLENGE_MEMBERS_COLLECTION_ID =process.env.EXPO_PUBLIC_CHALLENGE_MEMBERS_COLLECTION_ID!;
export const CHALLENGE_INVITES_COLLECTION_ID =process.env.EXPO_PUBLIC_CHALLENGE_INVITES_COLLECTION_ID!;
export const USER_PROFILE_COLLECTION_ID=process.env.EXPO_PUBLIC_USER_PROFILE_COLLECTION_ID!;
export const COMMUNITY_PROFILES_COLLECTION_ID =process.env.EXPO_PUBLIC_COMMUNITY_PROFILES_COLLECTION_ID!;
export const PROVIDER_ACCESS =process.env.EXPO_PUBLIC_PROVIDER_ACCESS_COLLECTION_ID!;
export const SHARED_REPORTS =process.env.EXPO_PUBLIC_SHARED_REPORTS_COLLECTION_ID!;


